# Generated by Django 5.2 on 2025-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
