# Generated by Django 5.2 on 2025-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_quiz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='true_quiz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
