# Generated by Django 5.2 on 2025-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_customuser_total_quiz_customuser_true_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
