# Generated by Django 5.2 on 2025-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(),
        ),
    ]
